name: Release Charm to Edge and Publish Libraries

on:
  push:
    branches:
      - main
      - track/**

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@c13b2b9fedaf3e22861bd15ae4e53ad6506b5523 # v1
    secrets: inherit
    with:
      default-track: 2
