name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**
  push:
    branches:
      - "renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@5127d643c26f438fe41b1068066ff281221e5d49 # v1
    secrets: inherit
