name: Terraform module tests

on:
  workflow_call:
    inputs:
      provider:
        description: |
          The substrate to set up prior to running the test
          (a concierge preset, e.g. 'machine' or 'microk8s').
        default: 'microk8s'
        required: false
        type: string

jobs:
    tf-tests:
        runs-on: ubuntu-latest
        name: Terraform tests
        steps:
          - name: Checkout
            uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
          - name: Install dependencies
            run: |
              sudo snap install concierge --classic
              sudo concierge prepare -p ${{ inputs.provider }} --extra-snaps terraform,astral-uv
          - name: Run tests
            run: |
              uvx tox -e terraform