name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable
      charm:
        type: choice
        description: Charm to promote
        options:
          - coordinator
          - worker

jobs:
  promote:
    name: Promote
    uses: canonical/observability/.github/workflows/charm-promote.yaml@v1
    with:
      promotion: ${{ github.event.inputs.promotion }}
      charm-path: ${{ github.event.inputs.charm }}
    secrets: inherit
