name: Tiobe TiCS Analysis

on:
    workflow_dispatch:
    schedule:
    - cron: "0 0 * * 1"  # Runs at midnight UTC every Monday

jobs:
    tics:
        name: TiCs
        uses: canonical/observability/.github/workflows/charm-tiobe-scan.yaml@5127d643c26f438fe41b1068066ff281221e5d49 # v1
        secrets: inherit
