name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

jobs:
  update-lib-coordinator:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@c13b2b9fedaf3e22861bd15ae4e53ad6506b5523 # v1
    secrets: inherit
    with:
      charm-path: coordinator
      git-branch: chore/auto-libs/coordinator
  update-lib-worker:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@c13b2b9fedaf3e22861bd15ae4e53ad6506b5523 # v1
    secrets: inherit
    with:
      charm-path: worker
      git-branch: chore/auto-libs/worker
